image: java:8-jdk

stages:
  - build
  - test
  - code_quality

before_script:
  - echo `Starting the pipeline`
  - echo `pwd` # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
     - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
  - docker:stable-dind
  script:
  - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
