image: java:8-jdk

stages:
  - build
  - test

before_script:
  - echo `Starting the pipeline`
  - echo `pwd` # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
     - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)